version: "3.9"

services:
  frontend-admin-develop:
    build:
      context: ../../Web-Admin
      dockerfile: ../Devops/develop/Dockerfile.app
    container_name: urbantracker-frontend-admin-develop
    restart: always
    env_file:
      - .env.develop
    ports:
      - "3000:3000"
    networks:
      - network_develop
    depends_on:
      - frontend-client-develop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend-client-develop:
    build:
      context: ../../Web-Client
      dockerfile: ../Devops/develop/Dockerfile.client
    container_name: urbantracker-frontend-client-develop
    restart: always
    env_file:
      - .env.develop
    ports:
      - "3001:3000"
    networks:
      - network_develop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  network_develop:
    driver: bridge
